# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ctios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ctios
  pod "CleverTap-iOS-SDK"
  pod "CleverTapLocation"

end
